const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{"Content-Type":"application/json"}});
async function verifyUser(url,anon,token){const r=await fetch(url+"/auth/v1/user",{headers:{apikey:anon,Authorization:"Bearer "+token}});return r.ok?r.json():null}
const host=ref=>{if(!ref)return"Direct";try{const h=new URL(ref).hostname.replace(/^www\./,"");if(h.includes("linkedin"))return"LinkedIn";if(h.includes("github"))return"GitHub";if(h.includes("google"))return"Google";if(h.includes("chatgpt")||h.includes("openai"))return"ChatGPT";return h}catch{return"Other"}};
const bucket=(map,k,n=1)=>map.set(k,(map.get(k)||0)+n);
const ranked=m=>[...m].map(([label,value])=>({label,value})).sort((a,b)=>b.value-a.value);
const projectName=(s="")=>{s=s.toLowerCase();if(s.includes("purple")||s.includes("active directory"))return"AD Purple Team Lab";if(s.includes("token"))return"Token Theft";if(s.includes("cowrie")||s.includes("honeypot"))return"Cowrie Honeypot";if(s.includes("gophish")||s.includes("phish"))return"GoPhish";if(s.includes("entra")||s.includes("azurehound")||s.includes("bloodhound"))return"Entra Attack Paths";if(s.includes("guardduty")||s.includes("aws"))return"AWS GuardDuty";return null};
const isBlog=(p="")=>p.includes("blog");
export default async(req)=>{
 if(req.method!=="GET")return json({error:"Method not allowed"},405);
 const url=Netlify.env.get("SUPABASE_URL"),anon=Netlify.env.get("SUPABASE_ANON_KEY"),service=Netlify.env.get("SUPABASE_SERVICE_ROLE_KEY"),admin=Netlify.env.get("ADMIN_EMAIL");
 if(!url||!anon||!service)return json({error:"Supabase is not configured yet"},503);
 const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,""),user=token&&await verifyUser(url,anon,token);
 if(!user)return json({error:"Authentication required"},401);if(admin&&String(user.email).toLowerCase()!==admin.toLowerCase())return json({error:"Not authorized"},403);
 const u=new URL(req.url),days=Math.max(1,Math.min(3650,Number(u.searchParams.get("days"))||7)),since=new Date(Date.now()-days*86400000).toISOString(),q=new URL(url+"/rest/v1/analytics_events");
 q.searchParams.set("select","created_at,event_type,session_id,page,title,referrer,referral_source,utm_source,country,device,active_seconds,scroll_depth,clicks");q.searchParams.set("created_at","gte."+since);q.searchParams.set("order","created_at.asc");q.searchParams.set("limit","10000");
 const rr=await fetch(q,{headers:{apikey:service,Authorization:"Bearer "+service}});if(!rr.ok)return json({error:"Analytics read failed"},500);const events=await rr.json(),pvs=events.filter(e=>e.event_type==="pageview");
 const sm=new Map();for(const e of events){if(!sm.has(e.session_id))sm.set(e.session_id,{id:e.session_id,events:[],pages:[],referrer:e.referrer||"",referral_source:e.referral_source||"",country:e.country||"",device:e.device||"unknown",active_seconds:0,scroll_depth:0,created_at:e.created_at,clicks:[]});const s=sm.get(e.session_id);s.events.push(e);s.active_seconds=Math.max(s.active_seconds,+e.active_seconds||0);s.scroll_depth=Math.max(s.scroll_depth,+e.scroll_depth||0);if(e.event_type==="pageview"&&!s.pages.includes(e.page))s.pages.push(e.page);for(const c of(Array.isArray(e.clicks)?e.clicks:[]))s.clicks.push(c)}
 const sessions=[...sm.values()].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));const avg=(a,f)=>a.length?Math.round(a.reduce((z,x)=>z+(+f(x)||0),0)/a.length):0;
 for(const s of sessions){const depth=Math.min(100,s.scroll_depth),time=Math.min(100,s.active_seconds/180*100),pages=Math.min(100,s.pages.length/3*100),click=Math.min(100,s.clicks.length/2*100);s.engagement_score=Math.round(depth*.3+time*.35+pages*.2+click*.15)}
 const pages=new Map(),sources=new Map(),devices=new Map(),clicks=new Map(),projects=new Map(),blogs=new Map(),daily=new Map(),journeys=new Map();
 const recruiter={project_views:0,github_clicks:0,cv_clicks:0,linkedin_clicks:0,contact_clicks:0,about_interest:0};
 for(const e of pvs){bucket(pages,e.page);const d=e.created_at.slice(0,10);bucket(daily,d);if(isBlog(e.page)){if(!blogs.has(e.page))blogs.set(e.page,{label:e.title||e.page,views:0,active:0,scroll:0});blogs.get(e.page).views++}}
 for(const s of sessions){bucket(sources,host(s.referrer));bucket(devices,s.device);if(s.pages.length)bucket(journeys,s.pages.join(" → "));if(s.pages.some(p=>p==="/"||p.includes("about")))recruiter.about_interest++;for(const e of s.events)if(isBlog(e.page)){const b=blogs.get(e.page);if(b){b.active=Math.max(b.active,+e.active_seconds||0);b.scroll=Math.max(b.scroll,+e.scroll_depth||0)}}for(const c of s.clicks){const label=(c.label||c.href||"Link"),low=(label+" "+(c.href||"")).toLowerCase();bucket(clicks,label);const pn=projectName(low);if(pn){if(!projects.has(pn))projects.set(pn,{label:pn,clicks:0});projects.get(pn).clicks++}if(low.includes("github"))recruiter.github_clicks++;if(low.includes("cv")||low.includes("resume"))recruiter.cv_clicks++;if(low.includes("linkedin"))recruiter.linkedin_clicks++;if(low.includes("mailto:")||low.includes("contact"))recruiter.contact_clicks++}}
 for(const e of pvs){const pn=projectName((e.page||"")+" "+(e.title||""));if(pn){if(!projects.has(pn))projects.set(pn,{label:pn,clicks:0});projects.get(pn).views=(projects.get(pn).views||0)+1;recruiter.project_views++}}
 const blogData=[...blogs.values()].map(b=>({label:b.label,views:b.views,avg_active_seconds:b.views?Math.round(b.active/b.views):0,avg_scroll_depth:b.views?Math.round(b.scroll/b.views):0})).sort((a,b)=>b.views-a.views);
 const projectData=[...projects.values()].map(x=>({...x,views:x.views||0})).sort((a,b)=>(b.views+b.clicks)-(a.views+a.clicks));
 return json({metrics:{unique_visitors:sessions.length,pageviews:pvs.length,avg_active_seconds:avg(sessions,x=>x.active_seconds),avg_scroll_depth:avg(sessions,x=>x.scroll_depth),avg_engagement_score:avg(sessions,x=>x.engagement_score)},top_pages:ranked(pages).slice(0,10),sources:ranked(sources).slice(0,10),devices:ranked(devices),clicks:ranked(clicks).slice(0,10),daily:ranked(daily).sort((a,b)=>a.label.localeCompare(b.label)),projects:projectData,blogs:blogData,journeys:ranked(journeys).slice(0,10),recruiter,sessions:sessions.slice(0,50)});
};