const $=id=>document.getElementById(id),loginPanel=$('login-panel'),dashboard=$('dashboard'),loginForm=$('login-form'),loginMessage=$('login-message'),statusEl=$('admin-status'),logoutBtn=$('logout-btn'),rangeSelect=$('range-select');
const authKey='mondli_admin_auth';let auth=JSON.parse(localStorage.getItem(authKey)||'null');
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmt=s=>{s=Math.max(0,+s||0);return s<60?s+'s':Math.floor(s/60)+'m '+Math.round(s%60)+'s'};
const sourceLabel=v=>{if(!v)return'Direct';const s=String(v).toLowerCase();if(s==='direct')return'Direct';if(s.includes('linkedin'))return'LinkedIn';if(s.includes('github'))return'GitHub';if(s.includes('google.'))return'Google';if(s.includes('bing.'))return'Bing';if(s.includes('duckduckgo'))return'DuckDuckGo';if(s.includes('facebook')||s.includes('fb.com'))return'Facebook';if(s.includes('twitter')||s.includes('x.com'))return'X / Twitter';if(s.includes('instagram'))return'Instagram';if(s.includes('chatgpt')||s.includes('openai'))return'ChatGPT';try{return new URL(v).hostname.replace(/^www\./,'')}catch{return String(v)==='Referral'?'Referral':String(v)}};
function list(id,items,fn=x=>x.value){$(id).innerHTML=items.length?items.map(x=>'<div class="admin-list-row"><span>'+esc(x.label)+'</span><strong>'+esc(fn(x))+'</strong></div>').join(''):'<div class="admin-empty">No data yet.</div>'}
async function api(path,o={}){const h={...(o.headers||{})};if(auth?.access_token)h.Authorization='Bearer '+auth.access_token;const r=await fetch(path,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
function bars(items){const el=$('trend-chart'),max=Math.max(1,...items.map(x=>x.value));el.innerHTML=items.length?items.map(x=>'<div class="bar-col"><div class="bar-value">'+x.value+'</div><div class="bar" style="height:'+Math.max(4,Math.round(x.value/max*140))+'px"></div><small>'+esc(x.label.slice(5))+'</small></div>').join(''):'<div class="admin-empty">No chart data yet.</div>'}
async function loadStats(){statusEl.textContent='Loading…';try{const d=await api('/.netlify/functions/admin-stats?days='+encodeURIComponent(rangeSelect.value));$('m-visitors').textContent=d.metrics.unique_visitors||0;$('m-pageviews').textContent=d.metrics.pageviews||0;$('m-engagement').textContent=(d.metrics.avg_engagement_score||0)+'/100';$('m-time').textContent=fmt(d.metrics.avg_active_seconds);$('m-scroll').textContent=(d.metrics.avg_scroll_depth||0)+'%';bars(d.daily||[]);list('sources',(d.sources||[]).map(x=>({...x,label:sourceLabel(x.label)})));list('top-pages',d.top_pages||[]);list('clicks',d.clicks||[]);list('projects',d.projects||[],x=>(x.views||0)+' · '+(x.clicks||0));list('blogs',d.blogs||[],x=>x.views+' · '+fmt(x.avg_active_seconds)+' · '+x.avg_scroll_depth+'%');list('journeys',d.journeys||[]);const r=d.recruiter||{};$('r-projects').textContent=r.project_views||0;$('r-github').textContent=r.github_clicks||0;$('r-cv').textContent=r.cv_clicks||0;$('r-linkedin').textContent=r.linkedin_clicks||0;$('r-contact').textContent=r.contact_clicks||0;const rows=d.sessions||[];$('session-count').textContent=rows.length+' shown';$('sessions-body').innerHTML=rows.length?rows.map(s=>'<tr><td>'+esc(new Date(s.created_at).toLocaleString())+'</td><td>'+esc((s.pages||[]).join(' → ')||'/')+'</td><td>'+esc(sourceLabel(s.referral_source||s.referrer))+'</td><td>'+esc(s.country||'Unknown')+'</td><td>'+esc(s.device)+'</td><td>'+fmt(s.active_seconds)+'</td><td>'+s.scroll_depth+'%</td><td><b>'+s.engagement_score+'</b></td></tr>').join(''):'<tr><td colspan="8">No analytics yet.</td></tr>';statusEl.textContent='Live';statusEl.classList.add('online')}catch(e){statusEl.textContent='Check setup';statusEl.classList.remove('online');if(/auth/i.test(e.message))logout()}}

let cmsType='blogs',cmsItems=[],cmsCurrent=null;
const schemas={
 blogs:[['title','Title','text'],['slug','Slug','text'],['summary','Summary','textarea'],['content','Article content (HTML supported)','textarea'],['category','Category','text'],['tags','Tags (comma separated)','csv'],['source_name','Source name','text'],['source_url','Source URL','url'],['published','Published','checkbox'],['featured','Featured','checkbox'],['display_order','Display order','number']],
 projects:[['title','Title','text'],['slug','Slug','text'],['description','Description','textarea'],['category','Category filters','text'],['technologies','Technologies (comma separated)','csv'],['bullets','Key points (one per line)','lines'],['github_url','GitHub URL','url'],['case_study','Case study','textarea'],['status','Status','text'],['published','Published','checkbox'],['featured','Featured','checkbox'],['display_order','Display order','number']],
 certifications:[['name','Name','text'],['provider','Provider','text'],['description','Description','textarea'],['status','Status','text'],['credential_url','Credential URL','url'],['published','Published','checkbox'],['display_order','Display order','number']],
 highlights:[['label','Highlight text','text'],['published','Published','checkbox'],['display_order','Display order','number']],
 settings:[['setting_key','Setting key','text'],['setting_value','Value','textarea']]
};
const labels={blogs:'Blog Posts',projects:'Projects',certifications:'Certifications',highlights:'Highlights',settings:'Site Settings'};
const displayName=(x)=>x.title||x.name||x.label||x.setting_key||'Untitled';
function fieldHtml([key,label,type],v){
 const val=v?.[key]??'';
 if(type==='checkbox')return '<label class="cms-check"><input name="'+key+'" type="checkbox" '+(val?'checked':'')+'> '+esc(label)+'</label>';
 if(type==='textarea'||type==='lines')return '<label>'+esc(label)+'<textarea name="'+key+'" rows="'+(key==='content'?10:5)+'">'+esc(type==='lines'&&Array.isArray(val)?val.join('\n'):val)+'</textarea></label>';
 if(type==='csv')return '<label>'+esc(label)+'<input name="'+key+'" value="'+esc(Array.isArray(val)?val.join(', '):val)+'"></label>';
 return '<label>'+esc(label)+'<input name="'+key+'" type="'+type+'" value="'+esc(val)+'"></label>';
}
function renderForm(item=null){cmsCurrent=item;$('cms-editor-title').textContent=item?'Edit '+labels[cmsType]:'New '+labels[cmsType];$('cms-state').textContent=item?(item.published===false?'Draft':'Saved'):'Unsaved';$('cms-fields').innerHTML=schemas[cmsType].map(f=>fieldHtml(f,item)).join('');$('cms-delete').hidden=!item}
function renderCmsList(){const el=$('cms-list');el.innerHTML=cmsItems.length?cmsItems.map(x=>'<button class="cms-item '+(cmsCurrent?.id===x.id?'active':'')+'" data-id="'+x.id+'"><span>'+esc(displayName(x))+'</span><small>'+(x.published===false?'Draft':'Published')+'</small></button>').join(''):'<div class="admin-empty">No items yet.</div>';el.querySelectorAll('.cms-item').forEach(b=>b.onclick=()=>{renderForm(cmsItems.find(x=>String(x.id)===b.dataset.id));renderCmsList()})}
async function loadCms(type=cmsType){cmsType=type;$('cms-list-title').textContent=labels[type];$('cms-message').textContent='';try{const d=await api('/.netlify/functions/admin-cms?type='+encodeURIComponent(type));cmsItems=d.items||[];cmsCurrent=null;renderCmsList();renderForm(null)}catch(e){$('cms-list').innerHTML='<div class="admin-empty">'+esc(e.message)+'</div>'}}
function formData(){const out={};for(const [key,,type] of schemas[cmsType]){const el=$('cms-form').elements[key];if(type==='checkbox')out[key]=el.checked;else if(type==='csv')out[key]=el.value.split(',').map(x=>x.trim()).filter(Boolean);else if(type==='lines')out[key]=el.value.split('\n').map(x=>x.trim()).filter(Boolean);else if(type==='number')out[key]=Number(el.value||0);else out[key]=el.value.trim()}return out}
$('cms-form').addEventListener('submit',async e=>{e.preventDefault();$('cms-message').textContent='Saving…';try{const body=formData(),path='/.netlify/functions/admin-cms?type='+encodeURIComponent(cmsType)+(cmsCurrent?'&id='+cmsCurrent.id:'');await api(path,{method:cmsCurrent?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('cms-message').textContent='Saved.';await loadCms(cmsType)}catch(e){$('cms-message').textContent=e.message}});
$('cms-delete').addEventListener('click',async()=>{if(!cmsCurrent||!confirm('Delete this item?'))return;try{await api('/.netlify/functions/admin-cms?type='+encodeURIComponent(cmsType)+'&id='+cmsCurrent.id,{method:'DELETE'});await loadCms(cmsType)}catch(e){$('cms-message').textContent=e.message}});
$('cms-new').addEventListener('click',()=>{cmsCurrent=null;renderForm(null);renderCmsList()});
document.querySelectorAll('.cms-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.cms-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');loadCms(b.dataset.type)}));
document.querySelectorAll('.admin-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.admin-tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.admin-view').forEach(v=>v.hidden=v.id!==b.dataset.view);if(b.dataset.view==='content-view')loadCms(cmsType)}));

function show(){loginPanel.hidden=true;dashboard.hidden=false;logoutBtn.hidden=false;loadStats()}
function logout(){auth=null;localStorage.removeItem(authKey);dashboard.hidden=true;loginPanel.hidden=false;logoutBtn.hidden=true;statusEl.textContent='Disconnected';statusEl.classList.remove('online')}
loginForm.addEventListener('submit',async e=>{e.preventDefault();loginMessage.textContent='Signing in…';try{auth=await api('/.netlify/functions/admin-auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('email').value,password:$('password').value})});localStorage.setItem(authKey,JSON.stringify(auth));loginMessage.textContent='';show()}catch(e){loginMessage.textContent=e.message}});
logoutBtn.addEventListener('click',logout);rangeSelect.addEventListener('change',loadStats);if(auth?.access_token)show();