(()=>{const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const blogHref=slug=>slug==='zero-trust-entra'?'blog-zero-trust-entra.html':slug==='service-principal-ownership-abuse'?'blog-service-principal-ownership-abuse.html':'blog.html?slug='+encodeURIComponent(slug);
async function load(){try{const r=await fetch('/.netlify/functions/cms-public?type=all');if(!r.ok)return;const d=await r.json();
 if(d.settings?.hero_subtitle){const el=document.querySelector('.hero-subtitle');if(el)el.textContent=d.settings.hero_subtitle}
 const about=document.querySelector('#about .section-copy');if(about){const ps=about.querySelectorAll('p');if(d.settings?.about_primary&&ps[0])ps[0].textContent=d.settings.about_primary;if(d.settings?.about_secondary&&ps[1])ps[1].textContent=d.settings.about_secondary}
 if(d.highlights?.length){const el=document.querySelector('.security-highlights-items');if(el)el.innerHTML=d.highlights.map(x=>'<span>'+esc(x.label)+'</span>').join('')}
 if(d.certifications?.length){const el=document.querySelector('.cert-grid');if(el)el.innerHTML=d.certifications.map(x=>'<article class="cert-card reveal visible"><span class="cert-state '+(String(x.status).toLowerCase().includes('progress')?'current':String(x.status).toLowerCase()==='next'?'future':'')+'">'+esc(x.status)+'</span><h3>'+esc(x.name)+'</h3><p>'+esc(x.description||x.provider||'')+'</p></article>').join('')}
 if(d.projects?.length){const el=document.querySelector('.project-grid');if(el)el.innerHTML=d.projects.map((x,i)=>{const tech=Array.isArray(x.technologies)?x.technologies:[],bullets=Array.isArray(x.bullets)?x.bullets:[];return '<article class="project-card reveal visible" data-category="'+esc(x.category||'')+'"><div class="project-number">'+String(i+1).padStart(2,'0')+'</div><div class="project-tags">'+tech.map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><h3>'+esc(x.title)+'</h3><p>'+esc(x.description||'')+'</p>'+(bullets.length?'<ul>'+bullets.map(b=>'<li>'+esc(b)+'</li>').join('')+'</ul>':'')+(x.github_url?'<a class="project-link" href="'+esc(x.github_url)+'" target="_blank" rel="noreferrer">View repository ↗</a>':'')+(x.case_study?'<div class="case-study open"><p>'+esc(x.case_study)+'</p></div>':'')+'</article>'}).join('')}
 if(d.blogs?.length){const el=document.querySelector('.blog-grid');if(el)el.innerHTML=d.blogs.map((x,i)=>'<article class="blog-card '+(x.featured?'featured ':'')+'reveal visible"><div class="blog-meta"><span class="blog-topic">'+esc(x.category||'Security')+'</span><time>'+esc(x.published_at?new Date(x.published_at).toLocaleDateString('en-ZA',{day:'2-digit',month:'short',year:'numeric'}):'')+'</time></div><h3>'+esc(x.title)+'</h3><p>'+esc(x.summary||'')+'</p><div class="blog-takeaways">'+(Array.isArray(x.tags)?x.tags:[]).map(t=>'<span>'+esc(t)+'</span>').join('')+'</div><div class="blog-source">Source: '+esc(x.source_name||'Research')+'</div><div class="blog-actions">'+(x.source_url?'<a href="'+esc(x.source_url)+'" target="_blank" rel="noreferrer">Original article ↗</a>':'')+'<a href="'+blogHref(x.slug)+'">Read my notes →</a></div></article>').join('')}
 }catch(_){}}
document.readyState==='loading'?document.addEventListener('DOMContentLoaded',load):load();})();