-- Run this in Supabase SQL Editor.
-- This schema intentionally does NOT store raw IP addresses.

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  event_type text not null,
  session_id text not null,
  page text not null,
  title text,
  referrer text,
  device text,
  active_seconds integer not null default 0,
  scroll_depth integer not null default 0,
  clicks jsonb not null default '[]'::jsonb,
  timezone text,
  language text,
  screen text
);

create index if not exists analytics_events_created_at_idx on public.analytics_events(created_at desc);
create index if not exists analytics_events_session_id_idx on public.analytics_events(session_id);
create index if not exists analytics_events_page_idx on public.analytics_events(page);

alter table public.analytics_events enable row level security;

-- No public table policies are required.
-- Netlify Functions use the service-role key server-side for reads/writes.
